# Generated by Django 4.1.7 on 2024-02-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_watchlist_auction_watchlist_auctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auctions',
            new_name='items',
        ),
    ]
