# Generated by Django 4.1.7 on 2024-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.IntegerField(),
        ),
    ]
