# Generated by Django 4.1.7 on 2024-02-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_start_value_alter_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
