# Generated by Django 4.1.7 on 2024-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_closed_auction_closed_time_auction_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='closed_time',
        ),
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
